# Generated by Django 2.1.1 on 2018-09-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sols_s', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
